package com.kodeelite.nooreislam.config.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Single source of truth for every app color (light + dark).
 *
 * Full Material 3 token set ("Serene Devotion" scheme) PLUS our own extras
 * (success/info/warning/neutral + UI surfaces). A color is declared once per mode.
 * Access in UI via [AppTheme.colors] (e.g. `AppTheme.colors.success`).
 */
@Immutable
data class AppColors(
    // ── Material 3: primary / secondary / tertiary / error ──
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    // ── Material 3: surfaces / background ──
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val outline: Color,
    val outlineVariant: Color,
    val surfaceTint: Color,
    val scrim: Color,
    // ── Material 3: fixed colors ──
    val primaryFixed: Color,
    val primaryFixedDim: Color,
    val onPrimaryFixed: Color,
    val onPrimaryFixedVariant: Color,
    val secondaryFixed: Color,
    val secondaryFixedDim: Color,
    val onSecondaryFixed: Color,
    val onSecondaryFixedVariant: Color,
    val tertiaryFixed: Color,
    val tertiaryFixedDim: Color,
    val onTertiaryFixed: Color,
    val onTertiaryFixedVariant: Color,
    // ── Extras: semantic ──
    val success: Color,
    val onSuccess: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val info: Color,
    val onInfo: Color,
    val infoContainer: Color,
    val onInfoContainer: Color,
    val warning: Color,
    val onWarning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    // ── Extras: UI surfaces ──
    val shadow: Color,
    val cardColor: Color,
    val scaffoldBackgroundColor: Color,
    val canvasColor: Color,
    val appbarColor: Color,
    val inputFieldIconColor: Color,
    // ── Extras: neutrals ──
    val neutral: Color,
    val onNeutral: Color,
    val neutralContainer: Color,
    val onNeutralContainer: Color,
    val neutralVariant: Color,
    val onNeutralVariant: Color,
    val neutralVariantContainer: Color,
    val onNeutralVariantContainer: Color,
    val neutralMuted: Color,
    val onNeutralMuted: Color,
    val neutralMutedContainer: Color,
    val onNeutralMutedContainer: Color,
    // ── App accent: prayers ──
    val fajrColor: Color, val onFajrColor: Color,
    val sunriseColor: Color, val onSunriseColor: Color,
    val dhuhrColor: Color, val onDhuhrColor: Color,
    val asrColor: Color, val onAsrColor: Color,
    val maghribColor: Color, val onMaghribColor: Color,
    val ishaColor: Color, val onIshaColor: Color,
    // ── App accent: tracker status ──
    val prayedColor: Color, val onPrayedColor: Color,
    val jamaatColor: Color, val onJamaatColor: Color,
    val kazaColor: Color, val onKazaColor: Color,
    val missedColor: Color, val onMissedColor: Color,
    // ── App accent: time status ──
    val currentColor: Color, val onCurrentColor: Color,
    val soonColor: Color, val onSoonColor: Color,
    val upcomingColor: Color, val onUpcomingColor: Color,
    val isDark: Boolean,
)

/** Light palette — "Serene Devotion" M3 + extras. Secondary softened to fit the green. */
fun lightAppColors() = AppColors(
    primary = Color(0xFF1E7D55),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB6EBD2),
    onPrimaryContainer = Color(0xFF003825),
    inversePrimary = Color(0xFF95D3BA),
    secondary = Color(0xFF4C6358),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCEE9DA),
    onSecondaryContainer = Color(0xFF34493F),
    tertiary = Color(0xFF25312B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF3B4741),
    onTertiaryContainer = Color(0xFFA8B5AD),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF8F9FA),
    onBackground = Color(0xFF191C1D),
    surface = Color(0xFFF8F9FA),
    onSurface = Color(0xFF191C1D),
    surfaceVariant = Color(0xFFE1E3E4),
    onSurfaceVariant = Color(0xFF404944),
    surfaceDim = Color(0xFFD9DADB),
    surfaceBright = Color(0xFFF8F9FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F4F5),
    surfaceContainer = Color(0xFFEDEEEF),
    surfaceContainerHigh = Color(0xFFE7E8E9),
    surfaceContainerHighest = Color(0xFFE1E3E4),
    inverseSurface = Color(0xFF2E3132),
    inverseOnSurface = Color(0xFFF0F1F2),
    outline = Color(0xFF707974),
    outlineVariant = Color(0xFFBFC9C3),
    surfaceTint = Color(0xFF2B6954),
    scrim = Color(0xFF000000),
    primaryFixed = Color(0xFFB0F0D6),
    primaryFixedDim = Color(0xFF95D3BA),
    onPrimaryFixed = Color(0xFF002117),
    onPrimaryFixedVariant = Color(0xFF0B513D),
    secondaryFixed = Color(0xFFCEE9DA),
    secondaryFixedDim = Color(0xFFB3CCBE),
    onSecondaryFixed = Color(0xFF09201A),
    onSecondaryFixedVariant = Color(0xFF34493F),
    tertiaryFixed = Color(0xFFD9E6DD),
    tertiaryFixedDim = Color(0xFFBDCAC1),
    onTertiaryFixed = Color(0xFF131E19),
    onTertiaryFixedVariant = Color(0xFF3E4943),
    success = Color(0xFF10B981),
    onSuccess = Color(0xFFFFFFFF),
    successContainer = Color(0xFFD1FAE5),
    onSuccessContainer = Color(0xFF064E3B),
    info = Color(0xFF3B82F6),
    onInfo = Color(0xFFFFFFFF),
    infoContainer = Color(0xFFDBEAFE),
    onInfoContainer = Color(0xFF1E3A8A),
    warning = Color(0xFFF59E0B),
    onWarning = Color(0xFFFFFFFF),
    warningContainer = Color(0xFFFEF3C7),
    onWarningContainer = Color(0xFF92400E),
    shadow = Color(0xFFE0E0E0),
    cardColor = Color(0xFFF3F4F5),
    scaffoldBackgroundColor = Color(0xFFF8F9FA),
    canvasColor = Color(0xFFF8F9FA),
    appbarColor = Color(0xFFF8F9FA),
    inputFieldIconColor = Color(0xFF404944),
    neutral = Color(0xFF757575),
    onNeutral = Color(0xFFFFFFFF),
    neutralContainer = Color(0xFFF5F5F5),
    onNeutralContainer = Color(0xFF212121),
    neutralVariant = Color(0xFF9E9E9E),
    onNeutralVariant = Color(0xFFFFFFFF),
    neutralVariantContainer = Color(0xFFEEEEEE),
    onNeutralVariantContainer = Color(0xFF616161),
    neutralMuted = Color(0xFFBDBDBD),
    onNeutralMuted = Color(0xFF000000),
    neutralMutedContainer = Color(0xFFE4E4E4),
    onNeutralMutedContainer = Color(0xFF757575),
    // prayers (deeper for light bg)
    fajrColor = Color(0xFF4F46E5), onFajrColor = Color(0xFFFFFFFF),
    sunriseColor = Color(0xFFEA580C), onSunriseColor = Color(0xFFFFFFFF),
    dhuhrColor = Color(0xFF0EA5E9), onDhuhrColor = Color(0xFFFFFFFF),
    asrColor = Color(0xFFD97706), onAsrColor = Color(0xFFFFFFFF),
    maghribColor = Color(0xFFE11D48), onMaghribColor = Color(0xFFFFFFFF),
    ishaColor = Color(0xFF6366F1), onIshaColor = Color(0xFFFFFFFF),
    // tracker status
    prayedColor = Color(0xFF16A34A), onPrayedColor = Color(0xFFFFFFFF),
    jamaatColor = Color(0xFF2563EB), onJamaatColor = Color(0xFFFFFFFF),
    kazaColor = Color(0xFFD97706), onKazaColor = Color(0xFFFFFFFF),
    missedColor = Color(0xFFDC2626), onMissedColor = Color(0xFFFFFFFF),
    // time status
    currentColor = Color(0xFF16A34A), onCurrentColor = Color(0xFFFFFFFF),
    soonColor = Color(0xFFD97706), onSoonColor = Color(0xFFFFFFFF),
    upcomingColor = Color(0xFF6B7280), onUpcomingColor = Color(0xFFFFFFFF),
    isDark = false,
)

/** Dark palette — "Serene Devotion" M3 + extras. Secondary softened to fit the green. */
fun darkAppColors() = AppColors(
    primary = Color(0xFF95D3BA),
    onPrimary = Color(0xFF003829),
    primaryContainer = Color(0xFF064E3B),
    onPrimaryContainer = Color(0xFF80BEA6),
    inversePrimary = Color(0xFF2B6954),
    secondary = Color(0xFFB3CCBE),
    onSecondary = Color(0xFF1F352B),
    secondaryContainer = Color(0xFF354B40),
    onSecondaryContainer = Color(0xFFCEE9DA),
    tertiary = Color(0xFFBDCAC1),
    onTertiary = Color(0xFF27332D),
    tertiaryContainer = Color(0xFF3B4741),
    onTertiaryContainer = Color(0xFFA8B5AD),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF111415),
    onBackground = Color(0xFFE1E3E4),
    surface = Color(0xFF111415),
    onSurface = Color(0xFFE1E3E4),
    surfaceVariant = Color(0xFF323536),
    onSurfaceVariant = Color(0xFFBFC9C3),
    surfaceDim = Color(0xFF111415),
    surfaceBright = Color(0xFF373A3B),
    surfaceContainerLowest = Color(0xFF0C0F10),
    surfaceContainerLow = Color(0xFF191C1D),
    surfaceContainer = Color(0xFF1D2021),
    surfaceContainerHigh = Color(0xFF282A2B),
    surfaceContainerHighest = Color(0xFF323536),
    inverseSurface = Color(0xFFE1E3E4),
    inverseOnSurface = Color(0xFF2E3132),
    outline = Color(0xFF89938D),
    outlineVariant = Color(0xFF404944),
    surfaceTint = Color(0xFF95D3BA),
    scrim = Color(0xFF000000),
    primaryFixed = Color(0xFFB0F0D6),
    primaryFixedDim = Color(0xFF95D3BA),
    onPrimaryFixed = Color(0xFF002117),
    onPrimaryFixedVariant = Color(0xFF0B513D),
    secondaryFixed = Color(0xFFCEE9DA),
    secondaryFixedDim = Color(0xFFB3CCBE),
    onSecondaryFixed = Color(0xFF09201A),
    onSecondaryFixedVariant = Color(0xFF34493F),
    tertiaryFixed = Color(0xFFD9E6DD),
    tertiaryFixedDim = Color(0xFFBDCAC1),
    onTertiaryFixed = Color(0xFF131E19),
    onTertiaryFixedVariant = Color(0xFF3E4943),
    success = Color(0xFF22C55E),
    onSuccess = Color(0xFF000000),
    successContainer = Color(0xFF14532D),
    onSuccessContainer = Color(0xFFBBF7D0),
    info = Color(0xFF60A5FA),
    onInfo = Color(0xFF000000),
    infoContainer = Color(0xFF1E3A8A),
    onInfoContainer = Color(0xFFDBEAFE),
    warning = Color(0xFFFBBF24),
    onWarning = Color(0xFF000000),
    warningContainer = Color(0xFF92400E),
    onWarningContainer = Color(0xFFFEF3C7),
    shadow = Color(0x1A000000),
    cardColor = Color(0xFF191C1D),
    scaffoldBackgroundColor = Color(0xFF111415),
    canvasColor = Color(0xFF111415),
    appbarColor = Color(0xFF1D2021),
    inputFieldIconColor = Color(0xFFBFC9C3),
    neutral = Color(0xFFB0BEC5),
    onNeutral = Color(0xFF1F1F1F),
    neutralContainer = Color(0xFF455A64),
    onNeutralContainer = Color(0xFFECEFF1),
    neutralVariant = Color(0xFF90A4AE),
    onNeutralVariant = Color(0xFF1F1F1F),
    neutralVariantContainer = Color(0xFF546E7A),
    onNeutralVariantContainer = Color(0xFFCFD8DC),
    neutralMuted = Color(0xFFE0E0E0),
    onNeutralMuted = Color(0xFF1F1F1F),
    neutralMutedContainer = Color(0xFF757575),
    onNeutralMutedContainer = Color(0xFFF5F5F5),
    // prayers (brighter for dark bg)
    fajrColor = Color(0xFF818CF8), onFajrColor = Color(0xFF000000),
    sunriseColor = Color(0xFFFB923C), onSunriseColor = Color(0xFF000000),
    dhuhrColor = Color(0xFF38BDF8), onDhuhrColor = Color(0xFF000000),
    asrColor = Color(0xFFFBBF24), onAsrColor = Color(0xFF000000),
    maghribColor = Color(0xFFFB7185), onMaghribColor = Color(0xFF000000),
    ishaColor = Color(0xFFA5B4FC), onIshaColor = Color(0xFF000000),
    // tracker status
    prayedColor = Color(0xFF4ADE80), onPrayedColor = Color(0xFF000000),
    jamaatColor = Color(0xFF60A5FA), onJamaatColor = Color(0xFF000000),
    kazaColor = Color(0xFFFBBF24), onKazaColor = Color(0xFF000000),
    missedColor = Color(0xFFF87171), onMissedColor = Color(0xFF000000),
    // time status
    currentColor = Color(0xFF4ADE80), onCurrentColor = Color(0xFF000000),
    soonColor = Color(0xFFFBBF24), onSoonColor = Color(0xFF000000),
    upcomingColor = Color(0xFF9CA3AF), onUpcomingColor = Color(0xFF000000),
    isDark = true,
)

/** Provides [AppColors] down the tree — Compose equivalent of Flutter's ThemeExtension. */
val LocalAppColors = staticCompositionLocalOf { lightAppColors() }

// the true, unoverridden app palette — QuranThemeHost re-provides LocalAppColors with the picked
// reading theme, so nested UI that needs the real app look (e.g. a "System" theme preview) reads this instead.
val LocalBaseAppColors = staticCompositionLocalOf { lightAppColors() }
